function representative_figure=fig_representative(wavelet_Xaxis_whole, wavelet_Yaxis_whole, waveletdata_whole, LFP_whole,... % whole
                        wavelet_Xaxis_epochs, wavelet_Yaxis_epochs, waveletdata_epochs, timesOFint, ind2cut)
               
                    
%% some definitions and conversion rules before figure is created
scrsz = get(0,'ScreenSize');
height4fig=scrsz(4)*0.8;
width4fig=height4fig/sqrt(2);
left4fig=(scrsz(3)-width4fig)/2;
bottom4fig=scrsz(4)*0.1;
figpos=[left4fig bottom4fig width4fig height4fig];

% Create figure
representative_figure = figure('Name','phases of individual experiments',...
    'Color',[0.94 0.94 0.94],...
    'PaperType','A4',...
    'PaperUnits','centimeters',...
    'PaperOrientation','Portrait',...
    'Position', figpos,...
    'Visible','off');

set(representative_figure,'PaperPosition', [0 0 get(representative_figure,'PaperSize')]);

% conversion factors
A4size_mm=get(representative_figure,'PaperSize')*10;
mm2points=0.352777778;

TWELVEpointsA4_mm=12/mm2points;
TWELVEpointsA4_relative=TWELVEpointsA4_mm/A4size_mm(2);

TENpointsA4_mm=10/mm2points;
TENpointsA4_relative=TENpointsA4_mm/A4size_mm(2);

EIGHTpointsA4_mm=8/mm2points;
EIGHTpointsA4_relative=EIGHTpointsA4_mm/A4size_mm(2);


%% Create wavelet axes
wavelet_axes = axes('Parent',representative_figure,'XMinorTick','on','TickDir','out',...
    'TickLength',[0.01 0.001],...
    'Position',[0.075 0.875 0.85 0.1],...    &'Layer','top',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontSize',TENpointsA4_relative,...
    'FontName','Arial');

MATversion=version;
if ((str2double(MATversion(end-5:end-2))-2014) + (~strcmp(MATversion(end-1),'a')))>0
colormap(wavelet_axes,parula)
else
load('parula_map');
colormap(wavelet_axes,parula_map)
end
totalTime_min=wavelet_Xaxis_whole(end);
xlim(wavelet_axes,[0 totalTime_min]);
ylim(wavelet_axes,[0.5 max(wavelet_Yaxis_whole)]);
hold(wavelet_axes,'all');

% Create image
image(wavelet_Xaxis_whole, wavelet_Yaxis_whole, waveletdata_whole,'Parent',wavelet_axes,'CDataMapping','scaled');
caxis([0, prctile(prctile(waveletdata_whole,99,1),99,2)])

% Create ylabel
text('String','Frequency [HZ]',...
    'Parent',wavelet_axes,...
    'Units', 'normalized',...
    'Position',[-0.055 0.5 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',TENpointsA4_relative,...
    'rotation',90,...
    'Color',[0.15 0.15 0.15]);

% Create xlabel
xlabel('time [min]',...
    'Units', 'normalized',...
    'Position',[0.5 -0.225 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',TENpointsA4_relative,...
    'Color',[0.15 0.15 0.15]);

% Create title
title('Morlet wavelet spectrum',...
    'Units', 'normalized',...
    'Position',[0.5 1.025 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','normalized',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',TWELVEpointsA4_relative,...
    'Color',[0.15 0.15 0.15]);

% Create colorbar
c = colorbar('peer',wavelet_axes,...
    'Units', 'normalized',...
    'Position',[0.93 0.875 0.01 0.1],...
    'FontName','Arial',...
    'Color',[0.15 0.15 0.15]);

wavelet_digits=fu_Digits(prctile(prctile(waveletdata_whole,99,1),99,2));
if isfield(get(c),'FontUnits')

set(c, 'FontUnits','normalized',...
       'FontSize',EIGHTpointsA4_relative)

oldlabels=get(c,'YTick');
newlabels=oldlabels*10^wavelet_digits;
newlabels=num2str(newlabels');
set(c,'YTickLabel',newlabels)
set(c,'YTickMode','manual')
clear oldlabels newlabels
else
oldlabels=get(c,'Ticks');
newlabels=oldlabels*10^wavelet_digits;
newlabels=num2str(newlabels');
set(c,'TickLabels',newlabels)
set(c,'YTickMode','manual')
clear oldlabels newlabels
end

% Create ylabel
str = sprintf('Power [(mV)^{%.3g}] x 10^{%.3g}',2,wavelet_digits*-1);
ylabel(c,str,...
    'Units','normalized',...
    'Position',[2.5 0.5 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontWeight','bold',....
    'FontSize',EIGHTpointsA4_relative,...
    'rotation',90,...
    'Color',[0.15 0.15 0.15]);
clear str

%% Create LFP axes for whole
LFP_axes_whole = axes('Parent',representative_figure,'XMinorTick','on','TickDir','out',...
    'TickLength',[0.01 0.001],...
    'Position',[0.075 0.71 0.85 0.1],...
    'FontUnits','normalized',...
    'FontSize',TENpointsA4_relative,...
    'FontName','Arial',...
    'Color','none',...
    'xlim',[0 totalTime_min],...
    'ylim',[-5 5]);    
    %'ylim',[prctile(LFP_whole,0.01,1) prctile(LFP_whole,99.99,1)]);
    %'ylim',[nanmin(LFP_whole) nanmax(LFP_whole)]);
hold(LFP_axes_whole,'all');

plot(totalTime_min/length(LFP_whole):totalTime_min/length(LFP_whole):totalTime_min,LFP_whole,'LineWidth',0.5,'Color','black','Parent',LFP_axes_whole)

% Create ylabel
text('String','LFP [mV]',...
    'Parent',LFP_axes_whole,...
    'Units', 'normalized',...
    'Position',[-0.055 0.5 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',TENpointsA4_relative,...
    'rotation',90,...
    'Color',[0.15 0.15 0.15]);

% Create xlabel
xlabel('time [min]',...
    'Units', 'normalized',...
    'Position',[0.5 -0.225 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',TENpointsA4_relative,...
    'Color',[0.15 0.15 0.15]);

% Create title
title('LFP overview',...
    'Units', 'normalized',...
    'Position',[0.5 1.025 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',TWELVEpointsA4_relative,...
    'Color',[0.15 0.15 0.15]);

%% epochs

numOFaxesLR=ceil(size(waveletdata_epochs,3)/2);
numOFaxesUD=ceil(size(waveletdata_epochs,3)/numOFaxesLR);
k=1;

for UD=1:numOFaxesUD
    for LR=1:numOFaxesLR
        if k<=length(timesOFint)
        dimX=(0.85-(0.05*(numOFaxesLR-1)))/numOFaxesLR;
        posX=0.075+(LR-1)*(dimX+0.05);
        posY=0.545+(1-UD)*(0.33);
        
%% Create multiple morlets on demand        
        wavelet_axes_ep(UD,LR) = axes('Parent',representative_figure,'XMinorTick','on','TickDir','out',...
            'TickLength',[0.01 0.001],...
            'Position',[posX posY dimX 0.1],...
            'FontUnits','normalized',...
            'FontSize',TENpointsA4_relative,...
            'FontName','Arial',...
            'xlim',[timesOFint(k)-wavelet_Xaxis_epochs(end) timesOFint(k)],...
            'ylim',[min(wavelet_Yaxis_epochs) max(wavelet_Yaxis_epochs)]);

hold(wavelet_axes_ep(UD,LR),'all');

% Create image
image(abs(wavelet_Xaxis_epochs-timesOFint(k)), wavelet_Yaxis_epochs, fliplr(waveletdata_epochs(:,:,k)),'Parent',wavelet_axes_ep(UD,LR),'CDataMapping','scaled');
caxis([0, prctile(prctile(squeeze(waveletdata_epochs(:,:,k)),99,1),99,2)])

% Create ylabel
if LR==1
text('String','Frequency [HZ]',...
    'Parent',wavelet_axes_ep(UD,LR),...
    'Units', 'normalized',...
    'Position',[-0.11 0.5 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',TENpointsA4_relative,...
    'rotation',90,...
    'Color',[0.15 0.15 0.15]);
end
% Create xlabel
xlabel('time [sec]',...
    'Units', 'normalized',...
    'Position',[0.5 -0.225 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',TENpointsA4_relative,...
    'Color',[0.15 0.15 0.15]);

% Create title
title('Morlet wavelet spectrum',...
    'Units', 'normalized',...
    'Position',[0.5 1.025 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','normalized',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',TWELVEpointsA4_relative,...
    'Color',[0.15 0.15 0.15]);



%% LFPs now

posY=0.38+(1-UD)*(0.33);


        LFP_axes_ep(UD,LR) = axes('Parent',representative_figure,'XMinorTick','on','TickDir','out',...
            'TickLength',[0.01 0.001],...
            'Position',[posX posY dimX 0.1],...
            'FontUnits','normalized',...
            'FontSize',TENpointsA4_relative,...
            'FontName','Arial',...
            'Color','none',...
            'xlim',[timesOFint(k)-wavelet_Xaxis_epochs(end) timesOFint(k)],...
            'ylim',[nanmin(LFP_whole(ind2cut(k,1):ind2cut(k,2))) nanmax(LFP_whole(ind2cut(k,1):ind2cut(k,2)))]);

hold(LFP_axes_ep(UD,LR),'all');

plot(timesOFint(k)-wavelet_Xaxis_epochs(end):wavelet_Xaxis_epochs(end)/diff(ind2cut(k,:),1,2):timesOFint(k),LFP_whole((ind2cut(k,1):(ind2cut(k,2))),1),'LineWidth',0.5,'Color','black','Parent',LFP_axes_ep(UD,LR))
if LR==1
text('String','LFP [mV]',...
    'Parent',LFP_axes_ep(UD,LR),...
    'Units', 'normalized',...
    'Position',[-0.11 0.5 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',TENpointsA4_relative,...
    'rotation',90,...
    'Color',[0.15 0.15 0.15]);
end
% Create xlabel
xlabel('time [sec]',...
    'Units', 'normalized',...
    'Position',[0.5 -0.225 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','normalized',...
    'FontName','Arial',...
    'FontWeight','bold',...
    'FontSize',TENpointsA4_relative,...
    'Color',[0.15 0.15 0.15]);

% Create title
title('LFP window of interest',...
    'Units', 'normalized',...
    'Position',[0.5 1.025 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','normalized',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',TWELVEpointsA4_relative,...
    'Color',[0.15 0.15 0.15]);

    k=1+k;    
        end    
    end
end
