function phase_figure=fig_Phases(wavlet_Xaxis, wavlet_Yaxis, wavletdata,... & wavelet
                        LFP_Xaxis, LFP_raw, LFP_filtered,... % LFP
                        PSD_Xaxis, PSD_median, PSD_BINs,... % PSD
                        PSDarea_Xaxis, PSDarea,... % PSD area
                        AutoCorr_Xaxis, autocorr_median, autocorr_BINs, autocorrfit, peaks4fit,... % autocorrelation
                        actualPhase, totalPhase, nameOFfile,...
                        wavelet_digits,LFP_maxmin,PSD_max,PSD_digits,autocorr_min)
               
                    
%% some definitions and conversion rules before figure is created
scrsz = get(0,'ScreenSize');
height4fig=scrsz(4)*0.8;
width4fig=height4fig/sqrt(2);
left4fig=(scrsz(3)-width4fig)/2;
bottom4fig=scrsz(4)*0.1;
figpos=[left4fig bottom4fig width4fig height4fig];

% Create figure
phase_figure = figure('Name','phases of individual experiments',...
    'Color',[0.94 0.94 0.94],...
    'PaperType','A4',...
    'PaperUnits','centimeters',...
    'PaperOrientation','Portrait',...
    'Position', figpos,...
    'Visible','off');

set(phase_figure,'PaperPosition', [0 0 get(phase_figure,'PaperSize')]);

% conversion factors
A4size_mm=get(phase_figure,'PaperSize')*10;
mm2points=0.352777778;

TWELVEpointsA4_mm=12/mm2points;
TWELVEpointsA4_relative=TWELVEpointsA4_mm/A4size_mm(2);

TENpointsA4_mm=10/mm2points;
TENpointsA4_relative=TENpointsA4_mm/A4size_mm(2);

EIGHTpointsA4_mm=8/mm2points;
EIGHTpointsA4_relative=EIGHTpointsA4_mm/A4size_mm(2);


%% Create wavelet axes
wavelet_axes = axes('Parent',phase_figure,'TickDir','out',...
    'Position',[0.125 0.7 0.75 0.2],...    &'Layer','top',...
    'FontUnits','points',...
    'FontName','Arial',...
    'FontSize',10);

MATversion=version;
if ((str2double(MATversion(end-5:end-2))-2014) + (~strcmp(MATversion(end-1),'a')))>0
colormap(wavelet_axes,parula) 
else
load('parula_map'); 
colormap(wavelet_axes,parula_map) 
end

xlim(wavelet_axes,[0 1]);
ylim(wavelet_axes,[0.5 100]);
hold(wavelet_axes,'all');

% Create image
image(wavlet_Xaxis, wavlet_Yaxis, wavletdata,'Parent',wavelet_axes,'CDataMapping','scaled');

% Create ylabel
text('String','Frequency [HZ]',...
    'Parent',wavelet_axes,...
    'Units', 'normalized',...
    'Position',[-0.1 0.5 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',10,...
    'rotation',90,...
    'Color',[0.15 0.15 0.15]);

%% Create xlabel
xlabel('time [s]',...
    'Units', 'normalized',...
    'Position',[0.5 -0.125 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',10,...
    'Color',[0.15 0.15 0.15]);

%% Create title
title('Morlet wavelet spectrum',...
    'Units', 'normalized',...
    'Position',[0.5 1.15 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',12,...
    'Color',[0.15 0.15 0.15]);

%% Create colorbar
c = colorbar('peer',wavelet_axes,...
    'Units', 'normalized',...
    'Position',[0.88 0.7 0.01 0.2],...
    'FontName','Arial',...
    'Color',[0.15 0.15 0.15]);
% caxis([0 3e-3]);  % added only for paper figures to determine a specific 
                    % scale of the colormap

if isfield(get(c),'FontUnits')

set(c, 'FontUnits','points',...
       'FontSize',8)

oldlabels=get(c,'YTick');
newlabels=oldlabels*10^wavelet_digits(actualPhase);
newlabels=num2str(newlabels');
set(c,'YTickLabel',newlabels)
set(c,'YTickMode','manual')
clear oldlabels newlabels
else
oldlabels=get(c,'Ticks');
newlabels=oldlabels*10^wavelet_digits(actualPhase);
newlabels=num2str(newlabels');
set(c,'TickLabels',newlabels)
set(c,'YTickMode','manual')
%set(c,'LimitsMode','manual');
%set(c,'Limits',[0 3]);
clear oldlabels newlabels
end

%% Create ylabel
str = sprintf('Power [mV^{%.3g}] x 10^{%.3g}',2,wavelet_digits(actualPhase)*-1);
ylabel(c,str,...
    'Units','normalized',...
    'Position',[4.5 0.5 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',8,...
    'rotation',90,...
    'Color',[0.15 0.15 0.15]);
clear str

set(wavelet_axes,'FontUnits','normalized')

%% Create LFP axes
LFP_axes = axes('Parent',phase_figure,'TickDir','out',...
    'Position',[0.125 0.4 0.75 0.2],...
    'xlim',[0 1],...
    'FontUnits','points',...
    'FontName','Arial',...
    'FontSize',10,...
    'ylim',[LFP_maxmin(2) LFP_maxmin(1)]);
hold(LFP_axes,'all');

plot(LFP_Xaxis, LFP_raw,'LineWidth',3,'Color',[86 180 233]./255,'Parent',LFP_axes)
plot(LFP_Xaxis, LFP_filtered,'LineWidth',1,'Color',[0 114 178]./255,'Parent',LFP_axes)

% Create ylabel
text('String','LFP [mV]',...
    'Parent',LFP_axes,...
    'Units', 'normalized',...
    'Position',[-0.1 0.5 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',10,...
    'rotation',90,...
    'Color',[0.15 0.15 0.15]);

% Create xlabel
xlabel('time [s]',...
    'Units', 'normalized',...
    'Position',[0.5 -0.125 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',10,...
    'Color',[0.15 0.15 0.15]);

% Create title
title('LocalFieldPotential',...
    'Units', 'normalized',...
    'Position',[0.5 1.15 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',12,...
    'Color',[0.15 0.15 0.15]);
set(LFP_axes,'FontUnits','normalized')

%% Create PSD axes
PSD_axes = axes('Parent',phase_figure,'XTick',[0 20 40 60 80 100],...
    'TickDir','out',...
    'FontUnits','points',...
    'FontSize',10,...
    'FontName','Arial',...
    'Position',[0.125 0.1 0.33 0.2],...
    'xlim',[0 100],...
    'ylim',[0 PSD_max(actualPhase)]);

hold(PSD_axes,'all');

if sum(isnan(PSDarea_Xaxis))+(PSDarea_Xaxis(1)<PSD_Xaxis(1))==0
% Create area
area(PSDarea_Xaxis,PSDarea,'FaceColor',[204 121 167]./255,'EdgeColor',[204 121 167]./255,'Parent',PSD_axes);
%plot(PSD_Xaxis,PSD_BINs,'Color',[0.5 0.5 0.5],'Parent',PSD_axes);
% Create plot
fu_shadedErrorBar(PSD_Xaxis,PSD_BINs,{@nanmedian,@(x,y) prctile(PSD_BINs,[75 25])},{'Color',[0 114 178]./255,'Linewidth',1});
plot([PSDarea_Xaxis(1) PSDarea_Xaxis(end)], [max(PSDarea)/2 max(PSDarea)/2],'Parent',PSD_axes,'LineWidth',2,'Color',[255 163 212]./255);
%plot(PSD_Xaxis,PSD_median,'Linewidth',2,'Color',[0 114 178]./255,'Parent',PSD_axes);
else
%plot(PSD_Xaxis,PSD_BINs,'Color',[0.5 0.5 0.5],'Parent',PSD_axes);
fu_shadedErrorBar(PSD_Xaxis,PSD_BINs,{@nanmedian,@(x,y) prctile(PSD_BINs,[75 25])},{'Color',[0 114 178]./255,'Linewidth',1});
end

%patch([PSD_Xaxis fliplr(PSD_Xaxis)],[prctile(PSD_BINs,97.5,1) fliplr(prctile(PSD_BINs,2.5,1))],[86 180 233]./255,'EdgeColor',[86 180 233]./255,'Parent',PSD_axes);
% plot(PSD_Xaxis,PSD_median,'Linewidth',2,'Color',[0 114 178]./255,'Parent',PSD_axes);


oldlabels=get(PSD_axes,'YTick');
newlabels=oldlabels*10^PSD_digits(actualPhase);
newlabels=num2str(newlabels');
set(PSD_axes,'YTickLabel',newlabels)
set(PSD_axes,'YTickMode','manual')
clear oldlabels newlabels

% Create ylabel
str = sprintf('PSD [mV^{%.3g}/Hz] x 10^{%.3g}',2,PSD_digits(actualPhase)*-1);
text('String',str,...
    'Parent',PSD_axes,...
    'Units', 'normalized',...
    'Position',[-0.1*(0.75/0.33) 0.5 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','bottom',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',10,...
    'rotation',90,...
    'Color',[0.15 0.15 0.15]);
clear str

% Create xlabel
xlabel('Frequency [Hz]',...
    'Units', 'normalized',...
    'Position',[0.5 -0.125 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',10,...
    'Color',[0.15 0.15 0.15]);

% Create title
title('PowerSpectralDensity',...
    'Units', 'normalized',...
    'Position',[0.5 1.15 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',12,...
    'Color',[0.15 0.15 0.15]);
set(PSD_axes,'FontUnits','normalized')

%% Create Autocorrelation axes
autocorr_axes = axes('Parent',phase_figure,'XTick',[0 20 40 60 80 100],'TickDir','out',...
    'Position',[0.545 0.1 0.33 0.2],...
    'FontUnits','points',...
    'FontSize',10,...
    'FontName','Arial',...
    'xlim',[0 100],...
    'ylim',[min(autocorr_min) 1]);
hold(autocorr_axes,'all');

%patch([AutoCorr_Xaxis fliplr(AutoCorr_Xaxis)],[prctile(autocorr_BINs,75,1) fliplr(prctile(autocorr_BINs,25,1))],[86 180 233]./255,'EdgeColor',[86 180 233]./255,'Parent',autocorr_axes);

% plot(AutoCorr_Xaxis,autocorr_BINs,'Color',[0.5 0.5 0.5],'Parent',autocorr_axes);
%plot(AutoCorr_Xaxis,autocorr_median,'Linewidth',2,'Color',[0 0 1],'Parent',autocorr_axes);

if ~isempty(autocorrfit)
%    [idx, centroid]=kmeans(peaks4fit(:,1),round(size(peaks4fit,1)/sum(~isnan(autocorr_BINs(:,1)))));
%    for i=1:max(idx)
%        
%        center(1)=median(peaks4fit(idx==i,1));
%        center(2)=median(peaks4fit(idx==i,2));
%        
%        %lower left
%        P2fit(1,1)=abs(prctile(peaks4fit(idx==i,1),2.5)-median(peaks4fit(idx==i,1)));
%        P2fit(1,2)=abs(prctile(peaks4fit(idx==i,2),2.5)-median(peaks4fit(idx==i,2)));
%        
%        %lower right
%        P2fit(2,1)=abs(prctile(peaks4fit(idx==i,1),97.5)-median(peaks4fit(idx==i,1)));
%        P2fit(2,2)=abs(prctile(peaks4fit(idx==i,2),2.5)-median(peaks4fit(idx==i,2)));
%        
%        %upper right
%        P2fit(3,1)=abs(prctile(peaks4fit(idx==i,1),97.5)-median(peaks4fit(idx==i,1)));
%        P2fit(3,2)=abs(prctile(peaks4fit(idx==i,2),97.5)-median(peaks4fit(idx==i,2)));
%        
%        %upper left
%        P2fit(4,1)=abs(prctile(peaks4fit(idx==i,1),2.5)-median(peaks4fit(idx==i,1)));
%        P2fit(4,2)=abs(prctile(peaks4fit(idx==i,2),97.5)-median(peaks4fit(idx==i,2)));
        
%         horz_rad=prctile(peaks4fit(idx==i,1),97.5)-prctile(peaks4fit(idx==i,1),2.5);
%         vert_rad=prctile(peaks4fit(idx==i,2),97.5)-prctile(peaks4fit(idx==i,2),2.5);

%        [x,y]= circularc(P2fit,center);
        
%        fill(x,y,[255 163 212]./255,'EdgeColor',[204 121 167]./255,'Parent',autocorr_axes);

%    end
%    fu_shadedErrorBar(AutoCorr_Xaxis,autocorr_BINs,{@nanmedian,@nanstd},{'Color',[0 114 178]./255,'Linewidth',1});
    fu_shadedErrorBar(AutoCorr_Xaxis,autocorr_BINs,{@nanmedian,@(x,y) prctile(autocorr_BINs,[75 25])},{'Color',[0 114 178]./255,'Linewidth',1,'Parent',autocorr_axes});
    plot(peaks4fit(:,1),peaks4fit(:,2),'o','Color',[0.5 0.5 0.5],'Parent',autocorr_axes)
    %plot(AutoCorr_Xaxis,autocorr_median,'Linewidth',2,'Color',[0 114 178]./255,'Parent',autocorr_axes);
    plot(AutoCorr_Xaxis,autocorrfit,'Linewidth',2,'Color',[204 121 167]./255,'Parent',autocorr_axes);
else
    fu_shadedErrorBar(AutoCorr_Xaxis,autocorr_BINs,{@nanmedian,@(x,y) prctile(autocorr_BINs,[75 25])},{'Color',[0 114 178]./255,'Linewidth',1});
    %plot(AutoCorr_Xaxis,autocorr_median,'Linewidth',2,'Color',[0 114 178]./255,'Parent',autocorr_axes);
end

set(autocorr_axes,'YTick',[0 0.5 1])

% set(autocorr_axes,'YTickMode','auto')
%set(autocorr_axes,'YTickLabelMode','manual')

% Create xlabel
xlabel('time [ms]',...
    'Units', 'normalized',...
    'Position',[0.5 -0.125 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',10,...
    'Color',[0.15 0.15 0.15]);

% Create title
title('Autocorrelation',...
    'Units', 'normalized',...
    'Position',[0.5 1.15 0],...
    'HorizontalAlignment','center',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',12,...
    'Color',[0.15 0.15 0.15]);

set(autocorr_axes,'FontUnits','normalized')

%% putting file information and phase number

if ~isempty(nameOFfile)
    underscoresinfile=strfind(nameOFfile,'_');
    spacesinfile=strfind(nameOFfile,' ');
    where2break=sort(horzcat(underscoresinfile,spacesinfile));
    % Create text
    if length(nameOFfile)<70
        temp_nameOFfile=nameOFfile;
    elseif length(nameOFfile)>60 && length(nameOFfile)<90
        [~, here2break]=min(abs(where2break-50));
        temp_nameOFfile=sprintf([nameOFfile(1:where2break(here2break)) '\n' nameOFfile(where2break(here2break)+1:end)]);
    else
        [~, here2break]=min(abs(where2break-70));
        temp_nameOFfile=sprintf([nameOFfile(1:where2break(here2break)) '\n' nameOFfile(where2break(here2break)+1:end)]);
    end
temp_nameOFfile(strfind(temp_nameOFfile,'_'))=' ';

text('Parent',wavelet_axes,'String',temp_nameOFfile,...
    'Units', 'normalized',...
    'Position',[-0.125 1.45 0],...
    'HorizontalAlignment','left',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',12,...
    'Color',[0.15 0.15 0.15]);
set(wavelet_axes,'FontUnits','normalized')
end

% Create text
text('Parent',wavelet_axes,'String',['Phase ' num2str(actualPhase) ' of ' num2str(totalPhase)],...
    'Units', 'normalized',...
    'Position',[1.125 1.45 0],...
    'HorizontalAlignment','right',...
    'VerticalAlignment','top',...
    'FontUnits','points',...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FontSize',12,...
    'Color',[0.15 0.15 0.15]);

set(wavelet_axes,'FontUnits','normalized')

